# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{csteamer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Cooper"]
  s.date = %q{2010-01-11}
  s.description = %q{CSteamer "steams" your content for data you can use in an organized way, such as a summary/first paragraph, del.icio.us tags, first image used in the content block, etc.}
  s.email = %q{git@peterc.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/csteamer.rb",
     "lib/csteamer/document.rb",
     "lib/csteamer/external_attributes.rb",
     "lib/csteamer/internal_attributes.rb",
     "test/corpus/bbcnews.html",
     "test/corpus/briancray.html",
     "test/corpus/huffington.html",
     "test/corpus/metadata_expected.yaml",
     "test/corpus/rubyinside.html",
     "test/corpus/rww.html",
     "test/corpus/techcrunch.html",
     "test/helper.rb",
     "test/test_corpus.rb",
     "test/test_csteamer_document.rb"
  ]
  s.homepage = %q{http://github.com/peterc/csteamer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Extracts or retrieves content-related metadata from HTML pages and remote services}
  s.test_files = [
    "test/helper.rb",
     "test/test_corpus.rb",
     "test/test_csteamer_document.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<mhennemeyer-matchy>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<loofah>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<mhennemeyer-matchy>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<loofah>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<mhennemeyer-matchy>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<loofah>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

